backend:
  name: github
  repo: Ins4h/RandomBlog
  branch: main

media_folder: static/assets
public_folder: /assets
collections:
  - name: blog
    label: Blog
    folder: src/data/blog
    create: true
    fields:
      - { name: id, widget: hidden, default: blog }
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }

  - name: quizz
    label: Quizz
    folder: src/data/quizzes
    create: true
    fields:
      - name: questionsList
        label: Zestaw Pytań
        widget: list
        fields:
          - name: questionContent
            label: Treść Pytania
            widget: string
          - name: possibleAnswers
            label: Ilość możliwych odpowiedzi
            widget: number
            default: 1
            value_type: int
            min: 1
          - name: answersList
            label: Zestaw Odpowiedzi
            widget: list
            fields:
              - name: answerContent
                label: Treść Odpowiedzi
                widget: string
              - name: isCorrect
                label: Czy odpowiedz jest poprawna
                widget: boolean
                default: false
  - name: test
    label: test
    folder: src/data/test
    create: true
    fields:
      - name: myWidget
        label: My Widget
        widget: questionsList
        fields:
          - name: content
            label: content
            widget: string
